In [1]:
import torch
## 1. Linear 함수 연산 과정
# https://www.youtube.com/watch?v=QpyXyenmtTA

Linear = torch.nn.Linear(5,8,bias=False)

print(Linear.weight.shape)
# print("레이어 가중치 초기화 전",Linear.weight)

torch.nn.init.constant_(Linear.weight[:,0],0)
torch.nn.init.constant_(Linear.weight[:,1],1)
torch.nn.init.constant_(Linear.weight[:,2],2)
torch.nn.init.constant_(Linear.weight[:,3],3)
torch.nn.init.constant_(Linear.weight[:,4],4)


print("레이어 가중치 초기화 후 (1)",Linear.weight)
print("Linear 레이어 계산을 위한 전치 행렬 프린트 (실제 연산에 적용될 웨이트)","\n",torch.transpose(Linear.weight,1,0))


row_0 = torch.range(0,4)
row_1 = torch.range(5,9)
row_2 = torch.range(10,14)
row_3 = torch.range(15,19)
row_4 = torch.range(20,24)

# print(row_0,row_1,row_2,row_3,row_4)

input = torch.vstack([row_0,row_1,row_2,row_3,row_4])
print(input.shape,"\n",input)


# print(row_0) 

print(Linear(input).shape,"\n",Linear(input))



## 행렬곱의 다른 표현
# print(input @ torch.transpose(Linear.weight,1,0))

torch.Size([8, 5])
레이어 가중치 초기화 후 (1) Parameter containing:
tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]], requires_grad=True)
Linear 레이어 계산을 위한 전치 행렬 프린트 (실제 연산에 적용될 웨이트) 
 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4., 4., 4.]], grad_fn=<TransposeBackward0>)
torch.Size([5, 5]) 
 tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.]])
torch.Size([5, 8]) 
 tensor([[ 30.,  30.,  30.,  30.,  30.,  30.,  30.,  30.],
        [ 80.,  80.,  80.,  80.,  80.,  80.,  80.,  80.],
        [130., 130., 130., 130., 130., 130., 130., 130.],


/data/mrjaehong/handwriting_gen/pytorch_vit/env/lib/python3.7/site-packages/ipykernel_launcher.py:21: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
/data/mrjaehong/handwriting_gen/pytorch_vit/env/lib/python3.7/site-packages/ipykernel_launcher.py:22: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
/data/mrjaehong/handwriting_gen/pytorch_vit/env/lib/python3.7/site-packages/ipykernel_launcher.py:23: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
/data/mrjaehong/handwriting_gen/pytorch_vit/env/lib/python3.7